export const descriptions = {
  repo_list_roots: "Use this when listing approved repositories. It does not read repository contents.",
  repo_policy_explain: "Use this when repository access is blocked or policy capabilities are unclear. It explains effective read, write, cleanup, validation, and Git-operation policy without mutation.",
  repo_last_write: "Use this when resuming after a write or checking what the latest write changed. It returns safe receipt metadata only.",
  repo_operation_ledger: "Use this when inspecting bounded historical write and operation receipts. Prefer repo_last_write for only the latest operation.",
  repo_tree: "Use this when locating directories and likely files by repository structure. Use repo_fetch_file to read contents.",
  repo_search: "Use this when locating code, text, usages, or likely files. Prefer it before reading multiple files.",
  repo_fetch_file: "Use this when reading one known file or line range. Do not use it for broad repository review.",
  repo_read_many: "Use this when reading a bounded known set of files or globs. Do not use it to read an entire repository.",
  repo_context_map: "Use this when mapping file-level impact, imports, dependents, entrypoints, routes, components, or affected tests. Use repo_symbol_context for symbol-level evidence.",
  repo_symbol_context: "Use this when gathering symbol-level evidence for definitions, references, calls, implementations, reverse dependents, or affected tests. Ask before starting an optional index.",
  repo_code_index: "Use this when checking or managing the optional Codebase Memory index. Before action=start, explicitly ask the user; status is safe to inspect without approval.",
  repo_failure_diagnose: "Use this when saved validation evidence needs normalized diagnostics and deterministic correlation. It does not run commands or claim an LLM root cause.",
  repo_semantic_review: "Use this when current changes need standalone evidence-based semantic risk review. Use repo_ship_review for combined final readiness.",
  repo_ship_review: "Use this when combined final readiness across Git, validation, semantic, and delegation gates is needed before ship. Compact is default; detail=full adds granular expert evidence and payloads.",
  repo_git_status: "Use this when checking branch, HEAD, cleanliness, or changed-file status. It does not read file contents.",
  repo_git_diff: "Use this when raw Git diff content is requested. Default first call should pass only repo_id; add filters only for a second pass.",
  repo_git_review: "Use this when reviewing current Git state or planning commit and recovery without mutation. Compact is default; detail=full adds granular and dry-run payloads.",
  repo_git_restore_paths: "Use this when explicitly restoring reviewed unstaged tracked paths. Prefer repo_write_recover for normal composite recovery.",
  repo_write_stage: "Use this when reviewed paths must be staged separately. Prefer the composite stage-and-commit payload when available.",
  repo_write_unstage: "Use this when reviewed paths must be unstaged separately. Prefer repo_write_recover for normal composite recovery.",
  repo_write_commit: "Use this when committing an exact already-staged path set locally. It verifies HEAD and staged paths and never pushes.",
  repo_write_stage_commit: "Use this when review returns the canonical stage-and-commit payload. Normal review supplies explicit paths; multi-run integration supplies only its opaque review_pathset_id. The server rechecks exact HEAD, bytes, paths, gates, and staged set, creates one local commit, and never pushes.",
  repo_write_recover: "Use this when review returns canonical composite recovery for explicit unstage, restore, cleanup, or discard paths. It never resets, stashes, pushes, or runs a shell.",
  repo_cleanup_paths: "Use this when separately deleting reviewed untracked generated or local artifacts allowed by cleanup policy. Prefer composite recovery when available.",
  repo_project_brief: "Use this when onboarding into or summarizing a repository. It returns repository-owned product context before technical metadata and never chooses the next goal.",
  repo_task_inventory: "Use this when the user explicitly requests TODO, FIXME, checkbox, roadmap, or backlog evidence. It returns candidates, not priority.",
  repo_decision_memory: "Use this when architecture rationale, conventions, or historical decisions are requested. It is supporting evidence, not product or active-work authority.",
  repo_change_plan: "Use this when the user and ChatGPT have already chosen an implementation goal. It plans how to execute that goal but never selects alternative work.",
  repo_prepare_codex_task: "Use this when previewing a product-grounded Delegation v3 task before writing it. Use complete review-provided payloads for lineage children.",
  repo_write_codex_task: "Use this when the user explicitly requests durable Codex or implementation-agent delegation. It writes bound Delegation v3 artifacts but never starts a runner, commits, or pushes.",
  repo_agent_runs: "Use this when inspecting agent lifecycle, runtime, questions, events, drift, or checkpoint state. It is read-only and never selects work.",
  repo_write_agent_reply: "Use this when answering the exact current structured questions for an awaiting-input run. It rejects stale or incomplete replies and only writes the reply artifact.",
  repo_continue_agent_run: "Use this when continuing an idle Codex App Server run through its private session.",
  repo_codex_review: "Use this when an implementation agent has finished. It validates bound result, scope, Git state, TAC/PAC evidence, technical readiness, and product-review requirements without self-approving product claims.",
  repo_write_codex_review: "Use this when recording the state-bound qualitative review returned by repo_codex_review. It validates the exact state and writes review evidence without staging or committing.",
  repo_write_integration_review: "Use this when the owner explicitly approves integrating multiple currently attested Delegation v3 runs in one worktree, and only for that integration case. It requires exact run, HEAD, pathset, validation, product-verdict, semantic, scope, and content state, then writes an opaque pathset for one atomic local commit; it is not a force or skip-review path.",
  repo_finalize_codex_run: "Use this when finalizing an exact terminal technical Delegation v3 run whose source changes already exist and require bounded provider-free closure. It revalidates the manifest-authorized pathset, creates one unsigned local commit, exports one verified committed-source archive, writes RESULT.json and terminal runner state, and never accepts a shell command, pushes, or contacts GitHub or a model.",
  repo_prepare_patchset: "Use this when preparing an atomic create, modify, edit, delete, or rename patchset. It writes only local manifest metadata, not target files.",
  repo_apply_patchset: "Use this when applying a prepared patchset atomically with stale-state guards. A HEAD-bound apply returns first-class rollback guidance.",
  repo_review_patchset: "Use this when reviewing a prepared or applied patchset and its ledger/Git state. It does not mutate files or Git.",
  repo_rollback_patchset: "Use this when the user explicitly approves rollback of an uncommitted, unchanged applied patchset. It requires the expected HEAD.",
  repo_validate: "Use this when running an allowlisted test, build, lint, typecheck, smoke, or all profile. A declared repo-owned make target takes priority; npm and safe pytest are fallbacks. Output is streamed into a bounded tail without a shell or arbitrary commands.",
  repo_start_work_session: "Use this when starting a focused multi-step slice that benefits from content-free local progress state.",
  repo_update_work_session: "Use this when appending decisions, inspected or touched paths, validation refs, risks, status, or next action to a work session.",
  repo_current_work_session: "Use this when resuming repository continuity. Current active or blocked work is full; completed history is compact unless work_session_id is supplied.",
  repo_write_file: "Use this when directly creating or precisely editing one allowed repository file. It supports stale-state guards and never runs Git, Codex, or a shell.",
  repo_write_changes: "Use this when directly applying one cohesive multi-file write/edit pack. It supports stale-state guards and never stages, commits, restores, or runs a shell.",
  repo_write_handoff: "Use this when the user asks for a local-only ChatGPT handoff: skapa handoff, create handoff, skriv handoff, session handoff, or resume note. It writes .chatgpt/handoffs/*.local.md and updates current.local.md without Git mutation.",
  repo_task_open: "Use this when opening one server-bound task from an exact base branch, commit, tree, authority, goal, and branch slug.",
  repo_task_status: "Use this when reading the current local binding, artifacts, and cleanup eligibility for one task.",
  repo_task_close: "Use this when closing an exact unchanged task HEAD and tree with a completed, blocked, abandoned, or superseded outcome.",
  repo_task_cleanup: "Use this when deleting only closed, server-owned task workspace resources and, when selected, its artifacts.",
  repo_artifact_read: "Use this when reading a bounded byte window from an opaque lifecycle artifact id; it never accepts a filesystem path.",
  repo_remote_status: "Use this when contacting GitHub to compare the bound task HEAD and tree with its exact remote refs without mutation.",
  repo_write_push: "Use this when fast-forward pushing the exact server-owned task branch through the fixed Git boundary; it never forces.",
  repo_pr_create_or_update: "Use this when creating or updating the Draft pull request derived from the exact task branch through GitHub.",
  repo_pr_status: "Use this when reading current GitHub pull-request state for the exact bound task branch.",
  repo_pr_review_threads: "Use this when reading bounded GitHub review threads for the pull request bound to the task.",
  repo_write_pr_reply: "Use this when posting one operation-bound reply to an exact review thread on the task pull request.",
  repo_write_pr_resolve_thread: "Use this when resolving one exact, version-bound review thread after its finding has been addressed.",
  repo_ci_status: "Use this when reading GitHub Actions runs and checks for the exact bound task HEAD and tree.",
  repo_write_ci_retry_failed: "Use this when retrying only exact failed GitHub Actions run ids from a bound CI status snapshot.",
  repo_merge_gate_prepare: "Use this when reading exact PR, review, and CI state to prepare an expiring merge manifest for owner CLI approval.",
  repo_write_merge: "Use this when consuming one exact unexpired owner-CLI approval to merge its bound manifest once.",
  repo_post_merge_readback: "Use this when reading GitHub after merge to confirm the exact PR, base ref, task ref, and merge commits.",
  repo_task_admission: "Use this when a coordinator or execution supervisor must distinguish an absent task, one exact matching active task, or conflicting active task state without mutation."
} as const;
